version: "3.9"

services:
  postgres:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: market
      POSTGRES_USER: aslugin
      POSTGRES_PASSWORD: 12345678
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "2345:80"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: slugin.alexander@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  db-data:
  pgadmin-data:
