version: "3.9"

services:
  postgres:
    image: postgres:16.1
    container_name: postgres
    restart: always
    ports:                        # DELETE FOR PRODUCTION
      - "5432:5432"
    environment:
      POSTGRES_DB: market
      POSTGRES_USER: aslugin
      POSTGRES_PASSWORD: 12345678
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "2345:80"
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: slugin.alexander@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase
    container_name: liquibase
    restart: on-failure
    command:
      - --changelog-file=changelog-master.xml
      - --url=jdbc:postgresql://postgres:5432/market
      - --driver=org.postgresql.Driver
      - --username=aslugin
      - --password=12345678
      - update
    volumes:
      - ./src/main/resources/db/migrations/:/liquibase/changelog/
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  db-data:
  pgadmin-data:

networks:
  backend:
    driver: bridge
